### ISSUE TITLE
Add dummy.mdx as default import (?)

### ISSUE THREAD

**Issue by Frotty** [wurstscript/WurstBareboneTemplate#1]
@Cokemonkey11 @peq @IgorSamurovic

See https://github.com/wurstscript/WurstStdlib2/blob/master/dummy/DummyRecycler.wurst#L157

The DummyRecycler package automatically generates the dummy unit for use with it and expects there to be a dummy.mdx, it might be advisable to package the required model file with this barebone repo.

However this would of course cause it to be always imported into any project even if not necessary.

**Comment by IgorSamurovic** [comment]
It is very lightweight, and you're extremely likely to use it.

Maybe obfuscate the path in some way, so that it is unlikely to clash with some other dummy unit or something? Like, make the dummy unit import to "!wurst/dummy.mdx" by default or something.

I wanted to comment on this when I was working on my map, I actually created my own dummy.mdx (with chest and head ref so that I can use forced facing) but having an absolutely standardized dummy.mdx import in every map sounds good.

Still, is there any way to make the dummy.mdx import ONLY if you have imported DummyRecycler somewhere? Are there some compiletime annotations/functions/functionalities for explicit importing?

**Comment by peq** [comment]
@Frotty are you suggesting to add the model to this example-project or integrate it into Wurst so that it gets added to every map? I don't see a problem of adding this to this example-project.

If we have real dependency management we can also think about whether dependencies can have resources that get imported automatically, but even then I would not add any default-imports to the standard library.

**Comment by Frotty** [comment]
@peq this "example" project is used when generating a project with the setup app, and yes, I would want to add it here ofc. Hardcoded in wurst doesn't seem to make sense.
